# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ExampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MoproBindings', :path => 'Frameworks/MoproBindings.podspec'
  pod 'CircuitBindings', :path => 'Frameworks/CircuitBindings.podspec'

  # Pods for ExampleApp

  target 'ExampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleAppUITests' do
    # Pods for testing
  end

end
